### ISSUE TITLE
De-wed from Spotify

### ISSUE THREAD

**Issue by john-bonachon** [jaedb/Iris#65]
I know this is kind of ankward, but it would be great to use Iris without spotify for those who doesn't have Premium accounts.

I've seen it works with another backends, i.e. Mopidy-Youtube, as its results are properly shown in Iris.

Is there any easy way (for you or us) to disable Spotify results from Iris?

That would make Iris a more general frontend and in my opinion the **best** around there.

**Comment by john-bonachon** [comment]
I don't know about React, so here is a very horrible hack,

```css
nav section:nth-child(2) {
  display: none;
}

.search-result-sections {
  display: none;
}
```

```js
setInterval(function(){
  $('.list-item.track .fa-spotify').parent().hide();
}, 200);
```
