### ISSUE TITLE
Docker Compose Failed start up

### ISSUE THREAD

**Issue by zanish** [jaedb/Iris#886]
Using Docker on a Debian LXC container. 

I cannot get Iris to start up using the docker compose in the getting started due to multiple errors.
1. meta_mopidy is nowhere to be found in the repo. As a new user to snapserver I don't ever really know where I should find this. 
2. start up breaks due to no server.json anywhere. 
3. Location of mopidy.conf is incorrect in the "getting started"

I'm trying to use docker since as I understand the Pip install still has the broken version of the spotify lib? The pip version installed easily but Docker seems to be impossible to spin up using the getting started section.

**Comment by shadowking001** [comment]
For the meta_mopidy.py file, you can get it there : [https://github.com/badaix/snapcast/blob/master/server/etc/plug-ins/meta_mpd.py](https://github.com/badaix/snapcast/blob/master/server/etc/plug-ins/meta_mpd.py)

I don't need any server.json file to spin up my containers.

The mopidy.conf file is mounted where you write it to be mounted :
![image](https://user-images.githubusercontent.com/43928955/217532919-4fa2feac-e81c-45cd-bb09-c558196f80ca.png)

**Comment by jaedb** [comment]
This has been pending a new release of Snapcast, which happened just a few days ago. I have updated the [Snapcast docker image](https://hub.docker.com/repository/docker/jaedb/snapserver/general) so this will use this new version, which contains `meta_mpd.py` baked-in.

You will need to read the documentation of Snapcast to explore all the options, but when defining your snapcast output in your Snapserver config (eg `/etc/snapserver.conf`) you can pass additional parameters to the control script definition to specify where your Mopidy server is running.

Last I checked it worked something like this (but you will need to confirm the exact syntax yourself):
```
stream = pipe:///tmp/snapfifo?name=Default&sampleformat=48000:16:2&controlscript=meta_mopidy.py&controlscriptparams=mopidy-host:my_hostname
```

Iris' out-of-box `docker-compose.yml` works without needing to tinker with these settings (you just need to rename the `-sample` files included in this repository).

**Comment by zanish** [comment]
Good Afternoon, I see you are running under docker exec and I am running docker compose. This is a freshly pulled repo and I get the following output.
![image](https://user-images.githubusercontent.com/6164442/218276461-edb594be-07d9-4b8a-a586-25d8ab18db69.png)

So OOTB it's not running on docker compose as of today without tinkering. I don't know if this is due to newer releases of docker compose that are conflicting with your set up but this is fresh as of today.

**Comment by jaedb** [comment]
When I say out-of-the-box, you still need to configure _some_ elements of the docker stack. Have you tried creating an empty `snapserver.json` (or omited it from your `docker-compose.yml` bindings)?

**Comment by shadowking001** [comment]
@jaedb the syntax has changed a bit for the `controlscriptparams`, see here : [https://github.com/badaix/snapcast/blob/develop/doc/configuration.md#sources](https://github.com/badaix/snapcast/blob/develop/doc/configuration.md#sources)

e.g.
`source = pipe:///tmp/snapfifo?name=Default&sampleformat=48000:16:2&controlscript=meta_mopidy.py&controlscriptparams=--mopidy-host=my_hostname%20--mopidy-port=16680`

You could close #883 too btw.

**Comment by remus-selea** [comment]
I have an issue with mopidy web interface not being accessible. I am running docker on an LXC on proxmox. I should be able to access the web interface at an ip like `192.168.10.12`. 

I followed the installation instructions at https://github.com/jaedb/Iris/wiki/Getting-started#installing, installed it with pip directly in the LXC. Even with this installation method I was not able to access the web interface. 
I managed to get it working after some time by modifying the `/etc/mopidy/mopidy.conf` file where I have added
```
[http]
enabled = true
hostname = 192.168.10.12
```
I was then able to see the interface at `http://192.168.10.12:6680/iris/` 

However I would like to get it running using docker. But I cannot get it to work with the compose example file and the `./docker/mopidy/mopidy.conf` file. The web UI just doesn't become accessible at all.

Here's my compose file:

```
version: "3"
services:
  snapserver:
    image: jaedb/snapserver:latest
    ports:
      - 1704:1704
      - 1705:1705
      - 1780:1780
    volumes:
      - /tmp/snapserver:/tmp
      - "./docker/snapserver/snapserver.conf:/etc/snapserver.conf"
      - "./docker/snapserver/snapserver.json:/root/.config/snapserver/server.json"

  mopidy:
    image: jaedb/iris:latest
    environment:
      - PIP_PACKAGES=Mopidy-YTMusic Mopidy-Tidal Mopidy-SoundCloud Mopidy-MusicBox-Webclient
    build:
      context: .
    depends_on:
      - snapserver
    ports:
      - 6600:6600
      - 6680:6680
    volumes:
      # - ./mopidy/iris:/iris/mopidy/iris # To use a locally-built UI 
      - ./docker/mopidy/iris:/var/lib/mopidy/iris # Iris-specific storage
      - ./docker/mopidy/m3u:/var/lib/mopidy/m3u # To persist local playlists
      - ./docker/mopidy/mopidy.conf:/config/mopidy.conf
      # - ./docker/mopidy/mopidy.conf:/etc/mopidy/mopidy.conf didn't work either
      - /mnt/host-data/data/audio/music:/var/lib/mopidy/media
      - /tmp/snapserver:/tmp
```
And the  `./docker/mopidy/mopidy.conf` file:

```
[core]
data_dir = /var/lib/mopidy

[audio]
#output = tee name=t ! queue ! autoaudiosink t. ! queue ! udpsink host=0.0.0.0 port=5555
output = audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! wavenc ! filesink location=/tmp/snapfifo

[http]
enabled = true
hostname = 192.168.10.12
port = 6680
zeroconf = Mopidy HTTP server on $hostname
allowed_origins = 
csrf_protection = true
default_app = iris

[mpd]
hostname = 192.168.10.12

[spotify]
# Fast startup because we use the Spotify HTTP API to load these instead
# Makes playlists unavailable under Browse > Spotify.
allow_playlists = false
```
